# Generated by Django 3.0.5 on 2020-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_score', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ppiscore',
            index=models.Index(fields=['protein1', 'protein2'], name='fuzzy_score_protein_c8b82c_idx'),
        ),
        migrations.AddIndex(
            model_name='ppiscore',
            index=models.Index(fields=['protein1'], name='protein1_idx'),
        ),
        migrations.AddIndex(
            model_name='ppiscore',
            index=models.Index(fields=['protein2'], name='protein2_idx'),
        ),
    ]
