# Generated by Django 3.0.5 on 2020-04-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_score', '0002_auto_20200430_1319'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ppiscore',
            name='protein1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ppiscore',
            name='protein2_idx',
        ),
    ]
